### ISSUE TITLE
Hardware VP9 not working on legacy devices running iOS 14+

### ISSUE THREAD

**Issue by PoomSmart** [PoomSmart/YTUHD#7]
A working `AVD.videodecoder` is required to register support for AV1 and VP9 codecs which will be used for 2K/4K resolutions.

Tracking issue: https://github.com/arandomdev/DyldExtractor/issues/31

**Comment by arandomdev** [comment]
After running `AVDRegister()` in the extracted iOS 14.6 AVD.videodecoder on a simulated iOS 14.6 iPhone SE 1st gen. I noticed that the following was logged, `AVDRegister - AppleAVDCheckPlatform() returned FALSE`. Looking into the disassembly, this prevents the registering of codecs.

![image](https://user-images.githubusercontent.com/40927866/148623996-4a80ee45-216a-4472-984c-099b65de9a28.png)

This does not occur on my iPhoneX, iOS 14.3, as `AVDRegister - AppleAVD HEVC codec registered` is logged instead.

Due to this, other things might also need to be patched.

**Comment by PoomSmart** [comment]
@arandomdev Do you believe that the real iPhone SE may have AppleAVD in the registry while the emulated one doesn't?

**Comment by arandomdev** [comment]
I highly doubt it, as Corellium prides themselves on making a near perfect emulation for security research. Of course, you can check the relevant key yourself with a small test program. Specifically, for the `AVCSupported` property.

**Comment by PoomSmart** [comment]
@arandomdev Do you have a working `AVD.videodecoder` binary that I can test?

**Comment by arandomdev** [comment]
Here is a signed binary that I created. Using the test program below I was able to run it on my iPhone X on iOS 14.3 and the simulated iPhone SE on iOS 14.6.

``` c
#include <dlfcn.h>
#include <stdio.h>

typedef void (AVDRegister_t)(void);

int main(int argc, char *argv[], char *envp[]) {
	NSLog(@"\x1b[36mHello!\x1b[0m\n");

	void *handle = dlopen("/Applications/TestEnv/AVD.videodecoder", RTLD_LAZY);
	AVDRegister_t *AVDRegister = (AVDRegister_t *)dlsym(handle, "AVDRegister");
	AVDRegister();

	NSLog(@"\x1b[36mGood Bye!\x1b[0m\n");
	return 0;
}

```

I did not need to set any environmental variables with this one.

[AVD.zip](https://github.com/PoomSmart/YTUHD/files/7834325/AVD.zip)

**Comment by PoomSmart** [comment]
@arandomdev That one actually can be `dlopen()`!. Something must went wrong on my end. Thanks!

**Comment by PoomSmart** [comment]
Loading `AppleAVD.kext` is required for all this to work, which is too much effort.

**Comment by arichorn** [comment]
#9 I listed the legacy devices in the new one and it’s only towards the devices with an A10X or older, A11-A15 is good enough for VP9
I’m bad at researching the hardware though so i don’t know if it’s fully accurate
